### ISSUE TITLE
A4+?

### ISSUE THREAD

**Issue by that-scientist** [chatziko/audioengine-a5-controller#2]
This is tremendous!  I lost my remote ages ago, and have never been able to buy one from audioengine, or find working IR codes anywhere.

Do you have any idea whether this could work on the older A4 speakers?

**Comment by chatziko** [comment]
I'm not familiar with A4 (and google doesn't seem to return any info). But if they have a rotary encoder and IR control it's likely doable.

Note that if you only need IR control (to replace the remote) it should be much easier, you just need to connect an IR transmitter to an ESP without messing with the speaker's internals.

**Comment by that-scientist** [comment]
Yup, I was wrong.  A5.  Man, I had that wrong for so many years...
